### ISSUE TITLE
is there any documentation that i can read to use typhon

### ISSUE THREAD

**Issue by objectizer** [monzo/typhon#65]
I am building a small app in a micro-services architecture, but i am still new to Go. I just saw the presentation by Mat Heath, and I was wondering if there is any documentation that i could rely on to build my services with Go. I have already wrote 3 services with Gin framework, but they still don't talk to each others, and so i thought typhon maybe a good option to build on top if it.

**Comment by mattheath** [comment]
Hey @objectizer, we don't have much documentation available currently I'm afraid. Typhon provides a transport and concepts of services, but unlike Gin doesn't emphasise being a web framework, so I'm not sure you'd benefit much from combining them?

If you're looking for a fully featured Go microservice framework I'd perhaps try [go-kit](https://github.com/go-kit/kit) or [micro](https://github.com/micro).
